export const data = [
    {
        id: '1',
        title: 'Agricultural Land Nkonkonjeru Mukono',
        price: 'UGX 20,000,000',
        location: 'Nkonkonjeru town, Bubwa village',
        size: '60 Acres',
        status: 'For Sale',
        image: 'https://i.imgur.com/n6DWTUo.jpg',
        screen: 'CategoryScreen',
    },
    {
        id: '2',
        title: 'Agricultural Land Nkonkonjeru Mukono',
        price: 'UGX 20,000,000',
        location: 'Nkonkonjeru town, Bubwa village',
        size: '60 Acres',
        status: 'For Sale',
        image: 'https://i.imgur.com/hukecEk.jpg',
        screen: 'CategoryScreen',
    },
    {
        id: '3',
        title: 'Agricultural Land Nkonkonjeru Mukono',
        price: 'UGX 20,000,000',
        location: 'Nkonkonjeru town, Bubwa village',
        size: '60 Acres',
        status: 'For Sale',
        image: 'https://i.imgur.com/n6DWTUo.jpg',
        screen: 'CategoryScreen',
    },
    {
        id: '4',
        title: 'Agricultural Land Nkonkonjeru Mukono',
        price: 'UGX 20,000,000',
        location: 'Nkonkonjeru town, Bubwa village',
        size: '60 Acres',
        status: 'For Sale',
        image: 'https://i.imgur.com/n6DWTUo.jpg',
        screen: 'CategoryScreen',
    },
    {
        id: '5',
        title: 'Agricultural Land Nkonkonjeru Mukono',
        price: 'UGX 20,000,000',
        location: 'Nkonkonjeru town, Bubwa village',
        size: '60 Acres',
        status: 'For Sale',
        image: 'https://i.imgur.com/n6DWTUo.jpg',
        screen: 'CategoryScreen',
    },
]