// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/home/jayp/Documents/react/LandVille-FrontEnd/node_modules/react');
var { Component } = React;
var ReactNative = require('/home/jayp/Documents/react/LandVille-FrontEnd/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('Propatiz', appParameters);
});
require('/home/jayp/Documents/react/LandVille-FrontEnd/index.js');